//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumericalAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _string {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _string() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumericalAnalysis.Properties.string", typeof(_string).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert inputs successfully..
        /// </summary>
        internal static string ConvertInputSuccess {
            get {
                return ResourceManager.GetString("ConvertInputSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisection Method failed..
        /// </summary>
        internal static string FailedChapter1_Bisection {
            get {
                return ResourceManager.GetString("FailedChapter1_Bisection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Position Method failed..
        /// </summary>
        internal static string FailedChapter1_FalsePos {
            get {
                return ResourceManager.GetString("FailedChapter1_FalsePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Position method failed: failed to Find Min Max of f&apos; on (a;b)..
        /// </summary>
        internal static string FailedChapter1_FalsePosition_CannotFindMinMax {
            get {
                return ResourceManager.GetString("FailedChapter1_FalsePosition_CannotFindMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Processing function ddf..
        /// </summary>
        internal static string FailedChapter1_Func_ddf {
            get {
                return ResourceManager.GetString("FailedChapter1_Func_ddf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Processing function df..
        /// </summary>
        internal static string FailedChapter1_Func_df {
            get {
                return ResourceManager.GetString("FailedChapter1_Func_df", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Processing function f..
        /// </summary>
        internal static string FailedChapter1_Func_f {
            get {
                return ResourceManager.GetString("FailedChapter1_Func_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gradient iterator failed to derivate.
        /// </summary>
        internal static string FailedChapter1_GradIterator_FailedDerivative {
            get {
                return ResourceManager.GetString("FailedChapter1_GradIterator_FailedDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newton Method failed..
        /// </summary>
        internal static string FailedChapter1_Newton {
            get {
                return ResourceManager.GetString("FailedChapter1_Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singular Iterative Method failed..
        /// </summary>
        internal static string FailedChapter1_SingularIterative {
            get {
                return ResourceManager.GetString("FailedChapter1_SingularIterative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singular Iterative method failed: failed to find Min Max of f&apos; on (a;b)..
        /// </summary>
        internal static string FailedChapter1_SingularIterative_CannotFindMinMax {
            get {
                return ResourceManager.GetString("FailedChapter1_SingularIterative_CannotFindMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Processing variable a..
        /// </summary>
        internal static string FailedChapter1_Var_a {
            get {
                return ResourceManager.GetString("FailedChapter1_Var_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Processing variable b..
        /// </summary>
        internal static string FailedChapter1_Var_b {
            get {
                return ResourceManager.GetString("FailedChapter1_Var_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Processing variable eps..
        /// </summary>
        internal static string FailedChapter1_Var_eps {
            get {
                return ResourceManager.GetString("FailedChapter1_Var_eps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file not detected, created file: FunctionInput.txt at .exe containing folder..
        /// </summary>
        internal static string NoInputFileChapter1 {
            get {
                return ResourceManager.GetString("NoInputFileChapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please recheck the input file first and press enter to retry..
        /// </summary>
        internal static string PleaseRecheckInput {
            get {
                return ResourceManager.GetString("PleaseRecheckInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 1 to select Bisection method 
        ///Type 2 to select False Position method 
        ///Type 3 to select Newton&apos;s method 
        ///Type 4 to select Singular Iterative method:.
        /// </summary>
        internal static string TypeInChapter1Switch {
            get {
                return ResourceManager.GetString("TypeInChapter1Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 1 to select Gauss method
        ///Type 2 to select Gauss Jordan method
        ///Type 3 to select LU decomposition
        ///Type 4 to select Jacobi method
        ///Type 5 to select Gauss-Seidel method
        ///Type 6 to select simple Iterative..
        /// </summary>
        internal static string TypeInChapter2Switch {
            get {
                return ResourceManager.GetString("TypeInChapter2Switch", resourceCulture);
            }
        }
    }
}
